<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>0.0.1</AssemblyVersion>
        <FileVersion>0.0.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <None Update="Assembler\64tass\win\64tass.exe">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assembler\64tass\linux-x64\64tass">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CodyNET.Assembler\CodyNET.Assembler.csproj" />
      <ProjectReference Include="..\CodyNET.Common\CodyNET.Common.csproj" />
      <ProjectReference Include="..\CodyNET.Disassembler\CodyNET.Disassembler.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.CommandLine" Version="2.0.2" />
    </ItemGroup>

</Project>
