// <auto-generated/>
using Xunit;
using CodyNET.Cody;

namespace CodyNET.Tests.SingleStep;

public sealed class SingleStepMnemonicTests_ADC
{
    [Fact]
    public void Minimal_ADC()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.ADC, options, output: null);
    }

    [Fact]
    public void Smoke_ADC()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.ADC, options, output: null);
    }

    [Fact]
    public void Full_ADC()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.ADC, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_AND
{
    [Fact]
    public void Minimal_AND()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.AND, options, output: null);
    }

    [Fact]
    public void Smoke_AND()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.AND, options, output: null);
    }

    [Fact]
    public void Full_AND()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.AND, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_ASL
{
    [Fact]
    public void Minimal_ASL()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.ASL, options, output: null);
    }

    [Fact]
    public void Smoke_ASL()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.ASL, options, output: null);
    }

    [Fact]
    public void Full_ASL()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.ASL, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBR0
{
    [Fact]
    public void Minimal_BBR0()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR0, options, output: null);
    }

    [Fact]
    public void Smoke_BBR0()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR0, options, output: null);
    }

    [Fact]
    public void Full_BBR0()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR0, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBR1
{
    [Fact]
    public void Minimal_BBR1()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR1, options, output: null);
    }

    [Fact]
    public void Smoke_BBR1()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR1, options, output: null);
    }

    [Fact]
    public void Full_BBR1()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR1, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBR2
{
    [Fact]
    public void Minimal_BBR2()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR2, options, output: null);
    }

    [Fact]
    public void Smoke_BBR2()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR2, options, output: null);
    }

    [Fact]
    public void Full_BBR2()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR2, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBR3
{
    [Fact]
    public void Minimal_BBR3()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR3, options, output: null);
    }

    [Fact]
    public void Smoke_BBR3()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR3, options, output: null);
    }

    [Fact]
    public void Full_BBR3()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR3, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBR4
{
    [Fact]
    public void Minimal_BBR4()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR4, options, output: null);
    }

    [Fact]
    public void Smoke_BBR4()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR4, options, output: null);
    }

    [Fact]
    public void Full_BBR4()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR4, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBR5
{
    [Fact]
    public void Minimal_BBR5()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR5, options, output: null);
    }

    [Fact]
    public void Smoke_BBR5()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR5, options, output: null);
    }

    [Fact]
    public void Full_BBR5()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR5, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBR6
{
    [Fact]
    public void Minimal_BBR6()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR6, options, output: null);
    }

    [Fact]
    public void Smoke_BBR6()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR6, options, output: null);
    }

    [Fact]
    public void Full_BBR6()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR6, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBR7
{
    [Fact]
    public void Minimal_BBR7()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR7, options, output: null);
    }

    [Fact]
    public void Smoke_BBR7()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR7, options, output: null);
    }

    [Fact]
    public void Full_BBR7()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR7, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBS0
{
    [Fact]
    public void Minimal_BBS0()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS0, options, output: null);
    }

    [Fact]
    public void Smoke_BBS0()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS0, options, output: null);
    }

    [Fact]
    public void Full_BBS0()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS0, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBS1
{
    [Fact]
    public void Minimal_BBS1()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS1, options, output: null);
    }

    [Fact]
    public void Smoke_BBS1()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS1, options, output: null);
    }

    [Fact]
    public void Full_BBS1()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS1, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBS2
{
    [Fact]
    public void Minimal_BBS2()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS2, options, output: null);
    }

    [Fact]
    public void Smoke_BBS2()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS2, options, output: null);
    }

    [Fact]
    public void Full_BBS2()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS2, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBS3
{
    [Fact]
    public void Minimal_BBS3()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS3, options, output: null);
    }

    [Fact]
    public void Smoke_BBS3()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS3, options, output: null);
    }

    [Fact]
    public void Full_BBS3()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS3, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBS4
{
    [Fact]
    public void Minimal_BBS4()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS4, options, output: null);
    }

    [Fact]
    public void Smoke_BBS4()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS4, options, output: null);
    }

    [Fact]
    public void Full_BBS4()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS4, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBS5
{
    [Fact]
    public void Minimal_BBS5()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS5, options, output: null);
    }

    [Fact]
    public void Smoke_BBS5()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS5, options, output: null);
    }

    [Fact]
    public void Full_BBS5()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS5, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBS6
{
    [Fact]
    public void Minimal_BBS6()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS6, options, output: null);
    }

    [Fact]
    public void Smoke_BBS6()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS6, options, output: null);
    }

    [Fact]
    public void Full_BBS6()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS6, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BBS7
{
    [Fact]
    public void Minimal_BBS7()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS7, options, output: null);
    }

    [Fact]
    public void Smoke_BBS7()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS7, options, output: null);
    }

    [Fact]
    public void Full_BBS7()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS7, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BCC
{
    [Fact]
    public void Minimal_BCC()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BCC, options, output: null);
    }

    [Fact]
    public void Smoke_BCC()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BCC, options, output: null);
    }

    [Fact]
    public void Full_BCC()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BCC, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BCS
{
    [Fact]
    public void Minimal_BCS()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BCS, options, output: null);
    }

    [Fact]
    public void Smoke_BCS()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BCS, options, output: null);
    }

    [Fact]
    public void Full_BCS()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BCS, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_BEQ
{
    [Fact]
    public void Minimal_BEQ()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BEQ, options, output: null);
    }

    [Fact]
    public void Smoke_BEQ()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BEQ, options, output: null);
    }

    [Fact]
    public void Full_BEQ()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BEQ, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_LDA
{
    [Fact]
    public void Minimal_LDA()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDA, options, output: null);
    }

    [Fact]
    public void Smoke_LDA()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDA, options, output: null);
    }

    [Fact]
    public void Full_LDA()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDA, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_LDX
{
    [Fact]
    public void Minimal_LDX()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDX, options, output: null);
    }

    [Fact]
    public void Smoke_LDX()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDX, options, output: null);
    }

    [Fact]
    public void Full_LDX()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDX, options, output: null);
    }
}

public sealed class SingleStepMnemonicTests_LDY
{
    [Fact]
    public void Minimal_LDY()
    {
        var options = TestOptions.Minimal();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDY, options, output: null);
    }

    [Fact]
    public void Smoke_LDY()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDY, options, output: null);
    }

    [Fact]
    public void Full_LDY()
    {
        var options = TestOptions.Full();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDY, options, output: null);
    }
}

