// <auto-generated/>
using NUnit.Framework;
using CodyNET.Cody;

namespace CodyNET.Tests.SingleStep;

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_ADC
{
    [Test]
    public void Smoke_ADC()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.ADC, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_AND
{
    [Test]
    public void Smoke_AND()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.AND, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_ASL
{
    [Test]
    public void Smoke_ASL()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.ASL, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBR0
{
    [Test]
    public void Smoke_BBR0()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR0, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBR1
{
    [Test]
    public void Smoke_BBR1()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR1, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBR2
{
    [Test]
    public void Smoke_BBR2()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR2, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBR3
{
    [Test]
    public void Smoke_BBR3()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR3, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBR4
{
    [Test]
    public void Smoke_BBR4()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR4, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBR5
{
    [Test]
    public void Smoke_BBR5()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR5, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBR6
{
    [Test]
    public void Smoke_BBR6()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR6, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBR7
{
    [Test]
    public void Smoke_BBR7()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBR7, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBS0
{
    [Test]
    public void Smoke_BBS0()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS0, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBS1
{
    [Test]
    public void Smoke_BBS1()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS1, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBS2
{
    [Test]
    public void Smoke_BBS2()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS2, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBS3
{
    [Test]
    public void Smoke_BBS3()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS3, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBS4
{
    [Test]
    public void Smoke_BBS4()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS4, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBS5
{
    [Test]
    public void Smoke_BBS5()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS5, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBS6
{
    [Test]
    public void Smoke_BBS6()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS6, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BBS7
{
    [Test]
    public void Smoke_BBS7()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BBS7, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BCC
{
    [Test]
    public void Smoke_BCC()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BCC, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BCS
{
    [Test]
    public void Smoke_BCS()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BCS, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_BEQ
{
    [Test]
    public void Smoke_BEQ()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.BEQ, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_LDA
{
    [Test]
    public void Smoke_LDA()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDA, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_LDX
{
    [Test]
    public void Smoke_LDX()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDX, options, output: null);
    }

}

[Parallelizable(ParallelScope.All)]
public sealed class SingleStepMnemonicTests_LDY
{
    [Test]
    public void Smoke_LDY()
    {
        var options = TestOptions.Smoke();
        // Pass null output to avoid interleaved logs in parallel runs.
        SingleStepMnemonicRunner.Run(Mnemonic.LDY, options, output: null);
    }

}

