using System.Text;
using NUnit.Framework;

namespace CodyNET.Tests.SingleStep;

public class TestGenerator
{
    [Test]
    public static void GenerateTests()
    {
        var source = GenerateSource();
        var projectDir = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", ".."));
        var targetPath = Path.Combine(projectDir, "SingleStep", "SingleStepMnemonicTests.g.cs");
        File.WriteAllText(targetPath, source);
    }
    
    private static string GenerateSource()
    {
        bool includeMinimal = false;
        bool includeSmoke = true;
        bool includeFull = false;
        // Keep this list in sync with your "working mnemonics".
        string[] mnemonics =
        [
            "ADC",
            "AND",
            "ASL",
            "BBR0","BBR1","BBR2","BBR3","BBR4","BBR5","BBR6","BBR7",
            "BBS0","BBS1","BBS2","BBS3","BBS4","BBS5","BBS6","BBS7",
            "BCC",
            "BCS",
            "BEQ",
            "LDA",
            "LDX",
            "LDY",
        ];

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using NUnit.Framework;");
        sb.AppendLine("using CodyNET.Cody;");
        sb.AppendLine();
        sb.AppendLine("namespace CodyNET.Tests.SingleStep;");
        sb.AppendLine();

        foreach (var mnemonic in mnemonics)
        {
            var className = $"SingleStepMnemonicTests_{mnemonic}";
            sb.AppendLine("[Parallelizable(ParallelScope.All)]");
            sb.AppendLine($"public sealed class {className}");
            sb.AppendLine("{");

            if (includeMinimal)
            {
                sb.AppendLine("    [Test]");
                sb.AppendLine($"    public void Minimal_{mnemonic}()");
                sb.AppendLine("    {");
                sb.AppendLine("        var options = TestOptions.Minimal();");
                sb.AppendLine("        // Pass null output to avoid interleaved logs in parallel runs.");
                sb.AppendLine($"        SingleStepMnemonicRunner.Run(Mnemonic.{mnemonic}, options, output: null);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            if (includeSmoke)
            {
                sb.AppendLine("    [Test]");
                sb.AppendLine($"    public void Smoke_{mnemonic}()");
                sb.AppendLine("    {");
                sb.AppendLine("        var options = TestOptions.Smoke();");
                sb.AppendLine("        // Pass null output to avoid interleaved logs in parallel runs.");
                sb.AppendLine($"        SingleStepMnemonicRunner.Run(Mnemonic.{mnemonic}, options, output: null);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            if (includeFull)
            {
                sb.AppendLine("    [Test]");
                sb.AppendLine($"    public void Full_{mnemonic}()");
                sb.AppendLine("    {");
                sb.AppendLine("        var options = TestOptions.Full();");
                sb.AppendLine("        // Pass null output to avoid interleaved logs in parallel runs.");
                sb.AppendLine($"        SingleStepMnemonicRunner.Run(Mnemonic.{mnemonic}, options, output: null);");
                sb.AppendLine("    }");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
