using System.Text;

namespace CodyNET.Tests.SingleStep;

public class TestGenerator
{
    //[Fact]
    public static void GenerateTests()
    {
        var source = GenerateSource();
        var projectDir = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", ".."));
        var targetPath = Path.Combine(projectDir, "SingleStep", "SingleStepMnemonicTests.g.cs");
        File.WriteAllText(targetPath, source);
    }
    
    private static string GenerateSource()
    {
        // Keep this list in sync with your "working mnemonics".
        string[] mnemonics =
        [
            "ADC",
            "AND",
            "ASL",
            "BBR0","BBR1","BBR2","BBR3","BBR4","BBR5","BBR6","BBR7",
            "BBS0","BBS1","BBS2","BBS3","BBS4","BBS5","BBS6","BBS7",
            "BCC",
            "BCS",
            "BEQ",
            "LDA",
            "LDX",
            "LDY",
        ];

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Xunit;");
        sb.AppendLine("using CodyNET.Cody;");
        sb.AppendLine();
        sb.AppendLine("namespace CodyNET.Tests.SingleStep;");
        sb.AppendLine();

        foreach (var mnemonic in mnemonics)
        {
            var className = $"SingleStepMnemonicTests_{mnemonic}";
            sb.AppendLine($"public sealed class {className}");
            sb.AppendLine("{");

            sb.AppendLine("    [Fact]");
            sb.AppendLine($"    public void Minimal_{mnemonic}()");
            sb.AppendLine("    {");
            sb.AppendLine("        var options = TestOptions.Minimal();");
            sb.AppendLine("        // Pass null output to avoid interleaved logs in parallel runs.");
            sb.AppendLine($"        SingleStepMnemonicRunner.Run(Mnemonic.{mnemonic}, options, output: null);");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    [Fact]");
            sb.AppendLine($"    public void Smoke_{mnemonic}()");
            sb.AppendLine("    {");
            sb.AppendLine("        var options = TestOptions.Smoke();");
            sb.AppendLine("        // Pass null output to avoid interleaved logs in parallel runs.");
            sb.AppendLine($"        SingleStepMnemonicRunner.Run(Mnemonic.{mnemonic}, options, output: null);");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    [Fact]");
            sb.AppendLine($"    public void Full_{mnemonic}()");
            sb.AppendLine("    {");
            sb.AppendLine("        var options = TestOptions.Full();");
            sb.AppendLine("        // Pass null output to avoid interleaved logs in parallel runs.");
            sb.AppendLine($"        SingleStepMnemonicRunner.Run(Mnemonic.{mnemonic}, options, output: null);");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}